name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - platform: amd64
            runs-on: ubuntu-latest
            docker-arch: ""
          - platform: arm64
            runs-on: ubuntu-latest
            docker-arch: "--platform linux/arm64"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
    - name: Set standalone env
      uses: ./.github/actions/set_standalone_env
      with:
        build-type: github

    - name: Test Benchmark Scripts
      run: |
        cd scripts/benchmarks
        python restful.py
        python pysdk.py
